FROM jupyter/datascience-notebook:7254cdcfa22b
RUN pip install --upgrade pip && \
    conda clean -tipsy && \
    mkdir desktop && \
    cd desktop && git clone https://github.com/mpilosov/ConsistentBayes.git


